
ALTER TABLE public.generated_labels
  ADD COLUMN IF NOT EXISTS pack TEXT,
  ADD COLUMN IF NOT EXISTS date_type TEXT,
  ADD COLUMN IF NOT EXISTS storage_instructions TEXT,
  ADD COLUMN IF NOT EXISTS quid_percent TEXT,
  ADD COLUMN IF NOT EXISTS nutrition_json JSONB,
  ADD COLUMN IF NOT EXISTS alcohol_abv NUMERIC,
  ADD COLUMN IF NOT EXISTS warnings_json JSONB,
  ADD COLUMN IF NOT EXISTS packaged_protective_atmosphere BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS nano BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS irradiated BOOLEAN DEFAULT FALSE;
